import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

import ExportButton from "./ExportButton";

const STATUS_STYLES = {
  Completed: "bg-green-100 text-green-700",
  Pending: "bg-yellow-100 text-yellow-700",
  Failed: "bg-red-100 text-red-700",
};

export default function ReportDetail() {

  const { id } = useParams();

  const navigate = useNavigate();

  /*
   * Temporary report data.
   *
   * We will replace this with backend data
   * once /reports/{id} API is implemented.
   */
  const report = {
    id,

    reportName: "Monthly Health Report",

    reportType: "Health",

    generatedBy: "ASHA Worker",

    createdAt: "10 July 2026",

    status: "Completed",

    totalBeneficiaries: 150,

    totalVisits: 320,

    summary:
      "This report contains monthly health records, visits and beneficiary statistics.",
  };


  return (

    <div className="space-y-6">

      {/* =========================================
          HEADER
      ========================================= */}

      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">

        <div className="flex items-center gap-3">

          {/* Back Button */}

          <button
            onClick={() => navigate("/app/reports")}
            className="rounded-lg border p-2 hover:bg-slate-100"
          >
            <ArrowLeft size={18} />
          </button>


          {/* Heading */}

          <div>

            <h1 className="text-3xl font-bold text-slate-900">
              Report Details
            </h1>

            <p className="text-slate-500">
              View complete report information.
            </p>

          </div>

        </div>


        {/* Export */}

        <ExportButton data={[report]} />

      </div>


      {/* =========================================
          REPORT DETAILS
      ========================================= */}

      <div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">

        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">

          <DetailItem
            label="Report Name"
            value={report.reportName}
          />


          <DetailItem
            label="Report Type"
            value={report.reportType}
          />


          <DetailItem
            label="Generated By"
            value={report.generatedBy}
          />


          <DetailItem
            label="Created Date"
            value={report.createdAt}
          />


          {/* Status */}

          <div>

            <p className="text-sm font-medium text-slate-500">
              Status
            </p>

            <span
              className={`mt-2 inline-block rounded-full px-3 py-1 text-sm font-semibold ${
                STATUS_STYLES[report.status]
              }`}
            >
              {report.status}
            </span>

          </div>

        </div>

      </div>


      {/* =========================================
          SUMMARY
      ========================================= */}

      <div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">

        <h2 className="text-lg font-bold text-slate-900">
          Report Summary
        </h2>


        <div className="mt-5 grid grid-cols-1 gap-5 md:grid-cols-3">

          <SummaryCard
            title="Beneficiaries"
            value={report.totalBeneficiaries}
          />


          <SummaryCard
            title="Total Visits"
            value={report.totalVisits}
          />


          <SummaryCard
            title="Report ID"
            value={report.id}
          />

        </div>


        <p className="mt-6 text-slate-600">
          {report.summary}
        </p>

      </div>

    </div>
  );
}


/* =========================================
   DETAIL ITEM
========================================= */

function DetailItem({
  label,
  value,
}) {

  return (

    <div>

      <p className="text-sm font-medium text-slate-500">
        {label}
      </p>

      <p className="mt-2 font-semibold text-slate-900">
        {value || "-"}
      </p>

    </div>
  );
}


/* =========================================
   SUMMARY CARD
========================================= */

function SummaryCard({
  title,
  value,
}) {

  return (

    <div className="rounded-xl bg-slate-50 p-5">

      <p className="text-sm text-slate-500">
        {title}
      </p>

      <p className="mt-2 text-2xl font-bold text-slate-900">
        {value ?? "-"}
      </p>

    </div>
  );
}