import React from "react";
import { useNavigate } from "react-router-dom";
import {
  Eye,
  Download,
  FileSpreadsheet,
  Trash2,
} from "lucide-react";


const STATUS_STYLES = {
  Completed: "bg-green-100 text-green-700",
  Pending: "bg-yellow-100 text-yellow-700",
  Failed: "bg-red-100 text-red-700",
};


export default function ReportTableRow({
  report,
  onDelete,
}) {

  const navigate = useNavigate();


  return (
    <tr className="border-t border-slate-100 transition hover:bg-slate-50">


      {/* Report Name */}
      <td className="px-6 py-4">

        <p className="font-semibold text-slate-900">
          {report.reportName}
        </p>

        <p className="mt-1 text-xs text-slate-400">
          ID: {report.id}
        </p>

      </td>



      {/* Type */}
      <td className="px-6 py-4 text-slate-700">

        {report.reportType}

      </td>



      {/* Generated By */}
      <td className="px-6 py-4 text-slate-700">

        {report.generatedBy}

      </td>



      {/* Date */}
      <td className="px-6 py-4 text-slate-700">

        {report.createdAt}

      </td>



      {/* Status */}
      <td className="px-6 py-4">

        <span
          className={`rounded-full px-3 py-1 text-xs font-semibold ${
            STATUS_STYLES[report.status] ||
            "bg-slate-100 text-slate-700"
          }`}
        >

          {report.status}

        </span>

      </td>



      {/* Actions */}
      <td className="px-6 py-4">

        <div className="flex justify-end gap-2">


          {/* View */}
          <button
            onClick={() =>
              navigate(`/app/reports/${report.id}`)
            }
            className="rounded-lg p-2 hover:bg-slate-100"
            title="View Report"
          >

            <Eye size={18} />

          </button>



          {/* PDF Download */}
          <button
            onClick={() =>
              console.log(
                "Download PDF",
                report.id
              )
            }
            className="rounded-lg p-2 hover:bg-slate-100"
            title="Download PDF"
          >

            <Download size={18} />

          </button>



          {/* Excel Export */}
          <button
            onClick={() =>
              console.log(
                "Export Excel",
                report.id
              )
            }
            className="rounded-lg p-2 hover:bg-slate-100"
            title="Export Excel"
          >

            <FileSpreadsheet size={18} />

          </button>



          {/* Delete */}
          <button
            onClick={() =>
              onDelete(report.id)
            }
            className="rounded-lg p-2 text-red-600 hover:bg-red-100"
            title="Delete Report"
          >

            <Trash2 size={18} />

          </button>


        </div>

      </td>


    </tr>
  );
}